openapi: 3.0.1
info:
  description: An API for interacting with data from Xpanse's Expander product.
  title: Entities
  version: 1.0.0
  termsOfService: https://www.paloaltonetworks.com/content/dam/pan/en_US/assets/pdf/legal/palo-alto-networks-end-user-license-agreement-eula.pdf
  contact:
    name: API Support
    url: https://docs.paloaltonetworks.com/cortex/cortex-xpanse/cortex-xpanse-user-guide/apis-and-integrations-main/expander-apis-and-integrations/expander-apis.html#expander-apis
    email: expanse-support@paloaltonetworks.com
servers:
  - url: https://expander.expanse.co
security:
  - Bearer: []
paths:
  /api/oauth2/RequestToken:
    post:
      tags:
        - Tokens
      summary: Get Access Token from Client Credentials
      description: "This route can be accessed with a `client_id` and `client_secret`\
          \ to generate a valid `access_token` to be used with the other Xpanse api\
          \ endpoints. For more information on how to retrieve client credentials, visit\
          \ the Xpanse [TechDocs](https://docs.paloaltonetworks.com/cortex/cortex-xpanse/cortex-xpanse-user-guide/apis-and-integrations-main/expander-apis-and-integrations/expander-apis.html#expander-apis).\
          \  \n\nExample: `Authorization: Bearer access_token`"
      operationId: getAccessToken
      requestBody:
        description: scope should be `scope-xpanse`, grant_type should be `client_credentials`
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                scope:
                  type: string
                  example: scope-xpanse
                grant_type:
                  type: string
                  example: client_credentials
      responses:
        "200":
          description: |-
            Response field `access_token` can be used as Bearer in future requests to other Xpanse endpoints.

            Example: `Authorization: Bearer access_token`
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer
                    example: 3599
      security:
        - ClientCredentials: []
      servers:
        - url: https://api.paloaltonetworks.com
  /api/v1/idToken/:
    get:
      tags:
        - Tokens
      summary: Get ID token from refresh token (Deprecated)
      description: |-
        This route can be accessed with an Xpanse-provided refresh
        token to generate a valid JWT Token to be used with the other api
        endpoints.

        Example: `Authorization: Bearer refreshtoken`
      operationId: getIdToken
      responses:
        "200":
          description: |-
            Response token can be used as JWT in future requests to other endpoints

            Example: `Authorization: JWT token`
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      security:
        - RefreshToken-Deprecated: []
  /api/v1/Entity/:
    get:
      summary: List Business Units
      description: Returns the list of Business Units to which the authenticated user has access.
      operationId: listBusinessUnits
      parameters:
        - name: name
          in: query
          required: false
          type: string
          description: Find an business unit by the given name
        - name: parent
          in: query
          required: false
          type: string
          format: uuid
          description: Find business units with the given parent business unit ID
        - name: has_parent
          in: query
          required: false
          type: string
          enum:
            - 'True'
            - 'False'
          description: Find business units that either have or do not have parents
      responses:
        '200':
          description: Business Unit list
          schema:
            type: array
            items:
              $ref: '#/definitions/Entity'
  /api/v1/Entity/{entityId}/:
    get:
      summary: Business Unit Details
      description: Returns the details for a given business unit.
      operationId: getBusinessUnitDetails
      parameters:
        - name: entityId
          in: path
          required: true
          type: string
          format: uuid
          description: ID for given Entity
      responses:
        '200':
          description: Business Unit details
          schema:
            $ref: '#/components/schemas/Entity'

components:
  schemas:
    Entity:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        parent:
          type: string
          format: uuid
          description: ID of parent Entity (may be null)
        resources:
          type: object
          description: A map of available asset types alongside the URL for fetching assets of that type for the given Entity
  securitySchemes:
    ClientCredentials:
      type: oauth2
      description: |-
        For more information on how to retrieve client credentials, visit the Xpanse [TechDocs](https://docs.paloaltonetworks.com/cortex/cortex-xpanse/cortex-xpanse-user-guide/apis-and-integrations-main/expander-apis-and-integrations/expander-apis.html#expander-apis). This is the preferred method for retrieving a JWT for Xpanse APIs. There will be significant customer communications and a lengthy migration period before refresh token support is removed in favor of the client credentials flow.

        Exchange a `client_id` and `client_secret` for an `access_token` (JWT) that can be passed to all Xpanse APIs. See [Get Access Token from Client Credentials](#operation/getAccessToken) for more info.
      flows:
        clientCredentials:
          tokenUrl: /api/oauth2/RequestToken
          scopes:
            scope-xpanse: access Xpanse APIs
    RefreshToken-Deprecated:
      type: apiKey
      description: |-
        Xpanse APIs continue to support this JWT retrieval method alongside the preferred client credentials flow. There will be significant customer communications and a lengthy migration period before refresh token support is removed in favor of the client credentials flow.

        Provide a valid Xpanse-provided refresh token to access `/api/v1/idToken/ This route will generate a JWT token that can be used with the other api endpoints.

        Example: `Authorization: Bearer <refreshToken>`
      name: Authorization
      in: header
    Bearer:
      type: http
      description: |-
        To access Xpanse APIs, a valid access token (JWT) must be included in every request
        in the `Authorization` header, which is retrieved by going through the client credentials flow (preferred method of JWT retrieval).

        The value for this header should be `Bearer <access_token>`, where the token is the base64-encoded JSON Web Token returned as the `access_token` field in the client credentials flow.
      name: Authorization
      in: header
      scheme: bearer
      bearerFormat: JWT

